services:

  Machinateur\TwigBlockValidator\Command\TwigBlockValidateCommand:
    public: true
    arguments:
      - '@Machinateur\TwigBlockValidator\Validator\TwigBlockValidator'
      - '@Machinateur\TwigBlockValidator\TwigBlockValidatorOutput'
      - '@twig'
    tags:
      - 'console.command'

  Machinateur\TwigBlockValidator\Validator\TwigBlockValidator:
    arguments:
      - '@twig_block_validator.twig'
      - '@Machinateur\TwigBlockValidator\Service\TwigBlockResolver'
      - '@event_dispatcher'

  Machinateur\TwigBlockValidator\TwigBlockValidatorOutput:
    tags:
      - 'kernel.event_subscriber'
      - { name: 'kernel.reset', method: 'reset' }

  Machinateur\TwigBlockValidator\Twig\BlockValidatorEnvironment:
    arguments:
      - '@twig'
      - '@twig_block_validator.cache'
      - '@event_dispatcher'
    tags:
      - { name: 'kernel.reset', method: 'reset' }

  twig_block_validator.twig:
    alias: 'Machinateur\TwigBlockValidator\Twig\BlockValidatorEnvironment'

  Machinateur\TwigBlockValidator\Command\TwigBlockAnnotateCommand:
    public: true
    arguments:
      - '@Machinateur\TwigBlockValidator\Annotator\TwigBlockAnnotator'
      - '@Machinateur\TwigBlockValidator\TwigBlockValidatorOutput'
      - '@twig'
    tags:
      - 'console.command'

  Machinateur\TwigBlockValidator\Annotator\TwigBlockAnnotator:
    arguments:
      - '@twig_block_validator.twig'
      - '@Machinateur\TwigBlockValidator\Service\TwigBlockResolver'
      - '@event_dispatcher'
    tags:
      - { name: 'kernel.reset', method: 'reset' }

  Machinateur\TwigBlockValidator\Service\TwigBlockResolver:
    arguments:
      - '@twig_block_validator.twig'

  Machinateur\TwigBlockValidator\Command\TwigBlockInspectCommand:
    public: true
    arguments:
      - '@Machinateur\TwigBlockValidator\Inspector\TwigBlockInspector'
      - '@Machinateur\TwigBlockValidator\TwigBlockValidatorOutput'
      - '@twig'
    tags:
      - 'console.command'

  Machinateur\TwigBlockValidator\Inspector\TwigBlockInspector:
    arguments:
      - '@twig_block_validator.twig'
      - '@Machinateur\TwigBlockValidator\Service\TwigBlockResolver'
      - '@event_dispatcher'
