services:

  Machinateur\TwigBlockValidator\Command\TwigBlockValidateCommand:
    arguments:
      - '@Machinateur\TwigBlockValidator\Validator\TwigBlockValidator'
      - '@Machinateur\TwigBlockValidator\Validator\TwigBlockValidatorOutput'
    tags:
      - 'console.command'

  Machinateur\TwigBlockValidator\Validator\TwigBlockValidator:
    arguments:
      - '@Machinateur\TwigBlockValidator\Twig\BlockValidatorEnvironment'
      - '@event_dispatcher'

  Machinateur\TwigBlockValidator\Validator\TwigBlockValidatorOutput:
    tags:
      - 'kernel.event_subscriber'

  Machinateur\TwigBlockValidator\Twig\BlockValidatorEnvironment:
    arguments:
      - '@twig'
      - '@twig_block_validator.block.cache'
      - '@twig_block_validator.comment.cache'

  Machinateur\TwigBlockValidator\Command\TwigBlockAnnotateCommand:
    arguments:
      - '@Machinateur\TwigBlockValidator\Validator\TwigBlockAnnotator'
      - '@Machinateur\TwigBlockValidator\Validator\TwigBlockAnnotatorOutput'
    tags:
      - 'console.command'
